-- Arabic storefront: optional per-language text on catalog rows,
-- e.g. {"ar": {"name": "…"}}. English stays in the existing columns and
-- is the fallback. Text below matches app/data/catalog-ar.ts.

-- AlterTable
ALTER TABLE "Category" ADD COLUMN     "translations" JSONB;

-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "translations" JSONB;

-- AlterTable
ALTER TABLE "PlanSlot" ADD COLUMN     "translations" JSONB;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "translations" JSONB;

UPDATE "Category" SET "translations" = '{"ar": {"name": "مشروبات مخمّرة", "blurb": "مشروبات حيّة مخمّرة — كومبوتشا وكفير وبيرة الزنجبيل."}}'::jsonb WHERE "slug" = 'beverages';
UPDATE "Category" SET "translations" = '{"ar": {"name": "أجبان وألبان", "blurb": "أجبان من حليب طبيعي وألبان مخمّرة، معتّقة وقابلة للدهن."}}'::jsonb WHERE "slug" = 'dairy';
UPDATE "Category" SET "translations" = '{"ar": {"name": "خضار مخمّرة", "blurb": "خضار مخمّرة ومتبّلة لمائدتك."}}'::jsonb WHERE "slug" = 'vegetables';
UPDATE "Category" SET "translations" = '{"ar": {"name": "زبدة المكسرات والدهون", "blurb": "زبدة مكسرات وبذور، ممزوجة بزيت الأركان وزيت الزيتون والعسل."}}'::jsonb WHERE "slug" = 'spreads';
UPDATE "Category" SET "translations" = '{"ar": {"name": "مربّيات ومنتجات الفاكهة", "blurb": "فاكهة على مهل — مربّيات ومركّزات وطماطم مجففة."}}'::jsonb WHERE "slug" = 'jams';
UPDATE "Category" SET "translations" = '{"ar": {"name": "أسماك ومأكولات بحرية", "blurb": "أسماك متبّلة وكفتة سمك، جاهزة للتقديم."}}'::jsonb WHERE "slug" = 'seafood';
UPDATE "Category" SET "translations" = '{"ar": {"name": "صلصات وتوابل", "blurb": "قواعد للطبخ وتوابل، محضّرة من الصفر."}}'::jsonb WHERE "slug" = 'sauces';
UPDATE "Product" SET "translations" = '{"ar": {"name": "بيرة الزنجبيل", "description": "مشروب زنجبيل منعش محضّر بالزنجبيل الطازج والليمون وسكر القصب، بنكهة جريئة طبيعية — مثالي للشرب أو للمزج.", "category": "مشروبات مخمّرة", "ingredients": ["زنجبيل", "سكر", "ماء", "ليمون"], "nutritionSummary": "الطاقة: 180 سعرة حرارية، البروتين: 0.2 غ، الكربوهيدرات: 44 غ، الدهون: 0 غ، الألياف: 0.2 غ، فيتامين C: 8 ملغ"}}'::jsonb WHERE "id" = 'prod-ginger-beer';
UPDATE "Product" SET "translations" = '{"ar": {"name": "كومبوتشا", "description": "كومبوتشا منعشة مخمّرة من الشاي الأسود والسكر والفواكه الموسمية — مشروب حامض غني بالبروبيوتيك يدعم صحة الأمعاء.", "category": "مشروبات مخمّرة", "ingredients": ["شاي أسود", "ماء", "سكر", "فواكه موسمية"], "nutritionSummary": "الطاقة: 18 سعرة حرارية، البروتين: 0 غ، الكربوهيدرات: 4.5 غ، الدهون: 0 غ، الألياف: 0 غ، فيتامين C: 2 ملغ"}}'::jsonb WHERE "id" = 'prod-kombucha';
UPDATE "Product" SET "translations" = '{"ar": {"name": "لبن", "description": "لبن كريمي من حليب طبيعي وخمائر كفير حيّة — غني بالبروبيوتيك ويمنح تغذيتك اليومية دفعة صحية بنكهة حامضة.", "category": "مشروبات مخمّرة", "ingredients": ["حليب طبيعي", "كفير الحليب"], "nutritionSummary": "الطاقة: 65 سعرة حرارية، البروتين: 3.3 غ، الكربوهيدرات: 4.7 غ، الدهون: 3.6 غ، الكالسيوم: 120 ملغ، بكتيريا نافعة: ~1x10^8 CFU"}}'::jsonb WHERE "id" = 'prod-leben';
UPDATE "Product" SET "translations" = '{"ar": {"name": "كفير الحليب", "description": "كفير حليب كريمي غني بالبروبيوتيك، محضّر من حليب طبيعي وخمائر حيّة — يدعم صحة الأمعاء بطعم حامض منعش.", "category": "مشروبات مخمّرة", "ingredients": ["حبيبات الكفير", "حليب طبيعي"], "nutritionSummary": "الطاقة: 65 سعرة حرارية، البروتين: 3.3 غ، الكربوهيدرات: 4.5 غ، الدهون: 3.6 غ، الكالسيوم: 120 ملغ، بكتيريا بروبيوتيك: ~1x10^9 CFU"}}'::jsonb WHERE "id" = 'prod-milk-kefir';
UPDATE "Product" SET "translations" = '{"ar": {"name": "كفير الماء", "description": "كفير ماء مخمّر طبيعيًا بالليمون والتين والفواكه الموسمية — منعش وحامض وغني بالبروبيوتيك.", "category": "مشروبات مخمّرة", "ingredients": ["حبيبات الكفير", "ماء", "سكر", "ليمون", "تين", "فواكه وأعشاب موسمية"], "nutritionSummary": "الطاقة: 30 سعرة حرارية، البروتين: 0.2 غ، الكربوهيدرات: 7 غ، الدهون: 0 غ، الألياف: 0.2 غ، فيتامين C: 4 ملغ"}}'::jsonb WHERE "id" = 'prod-water-kefir';
UPDATE "Product" SET "translations" = '{"ar": {"name": "جبن صلب", "description": "جبن صلب غني بالنكهة، مصنوع من حليب طبيعي وملح فقط — مثالي للتذوّق وأطباق الأجبان وإثراء وصفاتك المفضلة.", "category": "أجبان وألبان", "ingredients": ["حليب طبيعي", "ملح"], "nutritionSummary": "الطاقة: 400 سعرة حرارية، البروتين: 25 غ، الكربوهيدرات: 2 غ، الدهون: 33 غ، الكالسيوم: 800 ملغ"}}'::jsonb WHERE "id" = 'prod-hard-cheese';
UPDATE "Product" SET "translations" = '{"ar": {"name": "جبن", "description": "جبن مغربي طري وكريمي من حليب طبيعي ولمسة ملح — معتدل الطعم، مثالي للدهن أو للتذوّق أو لإضافته إلى أطباقك.", "category": "أجبان وألبان", "ingredients": ["حليب طبيعي", "ملح"], "nutritionSummary": "الطاقة: 220 سعرة حرارية، البروتين: 14 غ، الكربوهيدرات: 3 غ، الدهون: 16 غ، الكالسيوم: 400 ملغ"}}'::jsonb WHERE "id" = 'prod-jben';
UPDATE "Product" SET "translations" = '{"ar": {"name": "سمن", "description": "سمن مغربي تقليدي — زبدة مملّحة معتّقة بنكهة غنية — مثالي للكسكس والطواجن والأطباق المغاربية الأصيلة.", "category": "أجبان وألبان", "ingredients": ["زبدة", "ملح"], "nutritionSummary": "الطاقة: 720 سعرة حرارية، البروتين: 0.5 غ، الكربوهيدرات: 1 غ، الدهون: 80 غ، الألياف: 0 غ، الصوديوم: 1500 ملغ"}}'::jsonb WHERE "id" = 'prod-smen';
UPDATE "Product" SET "translations" = '{"ar": {"name": "جبن قابل للدهن", "description": "جبن كريمي قابل للدهن من حليب طبيعي، ممزوج بالثوم والزيتون والكمون والزعتر البري لنكهة متوسطية جريئة.", "category": "أجبان وألبان", "ingredients": ["حليب طبيعي", "ثوم", "زيتون", "كمون", "زعتر بري"], "nutritionSummary": "الطاقة: 320 سعرة حرارية، البروتين: 13 غ، الكربوهيدرات: 4 غ، الدهون: 28 غ، الألياف: 1 غ، الكالسيوم: 500 ملغ"}}'::jsonb WHERE "id" = 'prod-spread-cheese';
UPDATE "Product" SET "translations" = '{"ar": {"name": "باذنجان متبّل", "description": "باذنجان طري متبّل بالثوم والأعشاب الطازجة والتوابل العطرية في زيت الزيتون — مقبّلات أو طبق جانبي بنكهة متوسطية.", "category": "خضار مخمّرة", "ingredients": ["باذنجان", "ملح", "ثوم", "بقدونس طازج", "كزبرة طازجة", "توابل", "ورق الغار", "ماء", "زيت الزيتون"], "nutritionSummary": "الطاقة: 110 سعرة حرارية، البروتين: 1.2 غ، الكربوهيدرات: 5 غ، الدهون: 8 غ، الألياف: 3 غ، البوتاسيوم: 200 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-eggplants';
UPDATE "Product" SET "translations" = '{"ar": {"name": "زيتون متبّل", "description": "زيتون متبّل بالليمون والثوم وورق الغار والفلفل الحار — وجبة خفيفة أو مقبّلات متوسطية بنكهة جريئة لا تُقاوم.", "category": "خضار مخمّرة", "ingredients": ["زيتون طازج", "ملح", "ماء", "ليمون", "ثوم", "ورق الغار", "فلفل حار", "زيت الزيتون"], "nutritionSummary": "الطاقة: 210 سعرة حرارية، البروتين: 1.2 غ، الكربوهيدرات: 6 غ، الدهون: 21 غ، الألياف: 3 غ، الصوديوم: 1200 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-olives';
UPDATE "Product" SET "translations" = '{"ar": {"name": "خضار موسمية مخمّرة", "description": "مزيج ملوّن من الملفوف والجزر والشمندر المخمّر مع توابل عطرية — غني بالبروبيوتيك ويضيف لأي وجبة لمسة حامضة مفيدة للأمعاء.", "category": "خضار مخمّرة", "ingredients": ["ملفوف", "جزر", "شمندر", "ماء", "ثوم", "زنجبيل", "بصل", "كركم طازج", "ملح", "فلفل أسود", "ورق الغار", "عسل", "بذور الكزبرة", "بذور الخردل"], "nutritionSummary": "الطاقة: 40 سعرة حرارية، البروتين: 1.2 غ، الكربوهيدرات: 8 غ، الدهون: 0.3 غ، الألياف: 2.5 غ، فيتامين C: 18 ملغ، بكتيريا نافعة (Lactobacillus): موجودة"}}'::jsonb WHERE "id" = 'prod-seasonal-fermented-vegetables';
UPDATE "Product" SET "translations" = '{"ar": {"name": "أملو", "description": "أملو غني وكريمي من اللوز المحمّص وزيت الأركان الخالص والعسل — دهن طبيعي حلو ومغذٍّ، مثالي للفطور أو كوجبة خفيفة.", "category": "زبدة المكسرات والدهون", "ingredients": ["لوز", "زيت الأركان", "عسل"], "nutritionSummary": "الطاقة: 570 سعرة حرارية، البروتين: 13 غ، الكربوهيدرات: 25 غ، الدهون: 45 غ، الألياف: 7 غ، فيتامين E: 20 ملغ"}}'::jsonb WHERE "id" = 'prod-amlou';
UPDATE "Product" SET "translations" = '{"ar": {"name": "زبدة الفول السوداني", "description": "زبدة فول سوداني كريمية ممزوجة بزيت الأركان أو الزيتون أو السمسم حسب اختيارك، ومحلّاة بالعسل.", "category": "زبدة المكسرات والدهون", "ingredients": ["فول سوداني", "زيت الأركان/الزيتون/السمسم", "عسل"], "nutritionSummary": "الطاقة: 600 سعرة حرارية، البروتين: 22 غ، الكربوهيدرات: 18 غ، الدهون: 50 غ، الألياف: 6 غ، فيتامين E: 7 ملغ"}}'::jsonb WHERE "id" = 'prod-peanut-butter';
UPDATE "Product" SET "translations" = '{"ar": {"name": "زبدة الفستق", "description": "زبدة فستق كريمية ممزوجة بزيت الزيتون أو الأركان ولمسة عسل — دهن طبيعي حلو وغني بالعناصر الغذائية.", "category": "زبدة المكسرات والدهون", "ingredients": ["فستق", "زيت الزيتون/الأركان", "عسل"], "nutritionSummary": "الطاقة: 600 سعرة حرارية، البروتين: 18 غ، الكربوهيدرات: 20 غ، الدهون: 52 غ، الألياف: 8 غ، فيتامين E: 6 ملغ"}}'::jsonb WHERE "id" = 'prod-pistachio-butter';
UPDATE "Product" SET "translations" = '{"ar": {"name": "زبدة بذور اليقطين", "description": "زبدة بذور يقطين كريمية ممزوجة بزيت الزيتون والأركان ومحلّاة قليلًا بالعسل — دهن مغذٍّ بنكهة المكسرات.", "category": "زبدة المكسرات والدهون", "ingredients": ["بذور اليقطين", "زيت الزيتون/الأركان", "عسل"], "nutritionSummary": "الطاقة: 600 سعرة حرارية، البروتين: 25 غ، الكربوهيدرات: 15 غ، الدهون: 50 غ، الألياف: 6 غ، المغنيسيوم: 400 ملغ"}}'::jsonb WHERE "id" = 'prod-pumpkin-seed-butter';
UPDATE "Product" SET "translations" = '{"ar": {"name": "مربّيات", "description": "مربّيات محضّرة يدويًا من فواكه موسمية ناضجة وسكر القصب الأسمر — دهن حلو طبيعي للفطور أو الحلويات.", "category": "مربّيات ومنتجات الفاكهة", "ingredients": ["فواكه موسمية", "سكر القصب الأسمر"], "nutritionSummary": "الطاقة: 260 سعرة حرارية، البروتين: 0.5 غ، الكربوهيدرات: 65 غ، الدهون: 0.2 غ، الألياف: 1.5 غ، فيتامين C: 8 ملغ"}}'::jsonb WHERE "id" = 'prod-jams';
UPDATE "Product" SET "translations" = '{"ar": {"name": "مركّز الرمان", "description": "مركّز رمان غني بنكهة حامضة، محلّى بسكر القصب الأسمر — مثالي للمشروبات المنعشة والحلويات والوصفات.", "category": "مربّيات ومنتجات الفاكهة", "ingredients": ["رمان", "سكر القصب الأسمر"], "nutritionSummary": "الطاقة: 260 سعرة حرارية، البروتين: 1 غ، الكربوهيدرات: 65 غ، الدهون: 0 غ، الألياف: 1 غ، البوتاسيوم: 250 ملغ"}}'::jsonb WHERE "id" = 'prod-pomegranate-concentrate';
UPDATE "Product" SET "translations" = '{"ar": {"name": "طماطم مجففة", "description": "طماطم مجففة بالشمس ومتبّلة بزيت الزيتون والثوم والتوابل — تضيف نكهة متوسطية جريئة إلى السلطات والمعكرونة والمقبّلات.", "category": "مربّيات ومنتجات الفاكهة", "ingredients": ["طماطم", "ماء", "خل", "زيت الزيتون", "ثوم", "توابل"], "nutritionSummary": "الطاقة: 180 سعرة حرارية، البروتين: 4 غ، الكربوهيدرات: 30 غ، الدهون: 6 غ، الألياف: 7 غ، البوتاسيوم: 1100 ملغ"}}'::jsonb WHERE "id" = 'prod-sun-dried-tomatoes';
UPDATE "Product" SET "translations" = '{"ar": {"name": "أنشوجة متبّلة", "description": "أنشوجة طرية متبّلة بالثوم والأعشاب الطازجة والليمون والتوابل في زيت الزيتون — مثالية للمقبّلات والسلطات.", "category": "أسماك ومأكولات بحرية", "ingredients": ["أنشوجة", "ثوم", "أعشاب طازجة", "ليمون", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 210 سعرة حرارية، البروتين: 18 غ، الكربوهيدرات: 1 غ، الدهون: 15 غ، الألياف: 0 غ، الصوديوم: 1500 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-anchovies';
UPDATE "Product" SET "translations" = '{"ar": {"name": "أخطبوط متبّل", "description": "أخطبوط طري متبّل بالثوم والأعشاب الطازجة والليمون والتوابل في زيت الزيتون — مقبّلات أو سلطة فاخرة بنكهة متوسطية.", "category": "أسماك ومأكولات بحرية", "ingredients": ["أخطبوط", "ثوم", "أعشاب طازجة", "ليمون", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 120 سعرة حرارية، البروتين: 16 غ، الكربوهيدرات: 2 غ، الدهون: 5 غ، الألياف: 0.5 غ، الحديد: 4 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-octopus';
UPDATE "Product" SET "translations" = '{"ar": {"name": "سردين متبّل", "description": "سردين طري متبّل بالثوم والأعشاب الطازجة والليمون والتوابل في زيت الزيتون — جاهز للتقديم بنكهة متوسطية غنية.", "category": "أسماك ومأكولات بحرية", "ingredients": ["سردين", "ثوم", "أعشاب طازجة", "ليمون", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 210 سعرة حرارية، البروتين: 22 غ، الكربوهيدرات: 0 غ، الدهون: 14 غ، الألياف: 0 غ، الكالسيوم: 250 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-sardines';
UPDATE "Product" SET "translations" = '{"ar": {"name": "تونة متبّلة", "description": "تونة طرية متبّلة بالثوم والأعشاب الطازجة والليمون والتوابل في زيت الزيتون — وجبة أو وجبة خفيفة جاهزة ولذيذة.", "category": "أسماك ومأكولات بحرية", "ingredients": ["تونة", "ثوم", "أعشاب طازجة", "ليمون", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 180 سعرة حرارية، البروتين: 23 غ، الكربوهيدرات: 1 غ، الدهون: 9 غ، الألياف: 0.5 غ، الحديد: 1.2 ملغ"}}'::jsonb WHERE "id" = 'prod-marinated-tuna';
UPDATE "Product" SET "translations" = '{"ar": {"name": "كفتة السردين بصلصة الطماطم", "description": "كفتة سردين طرية بالثوم والبقدونس الطازج والتوابل في صلصة طماطم منعشة — لمسة أصيلة على المطبخ المتوسطي.", "category": "أسماك ومأكولات بحرية", "ingredients": ["سردين", "ثوم", "بقدونس طازج", "توابل", "ليمون", "صلصة الطماطم"], "nutritionSummary": "الطاقة: 160 سعرة حرارية، البروتين: 15 غ، الكربوهيدرات: 4 غ، الدهون: 9 غ، الألياف: 1 غ، الكالسيوم: 250 ملغ"}}'::jsonb WHERE "id" = 'prod-sardine-kefta-in-tomato-sauce';
UPDATE "Product" SET "translations" = '{"ar": {"name": "كفتة النازلي بصلصة الطماطم", "description": "كفتة سمك النازلي بالثوم والبقدونس والتوابل، مطهوّة في صلصة طماطم منعشة — وجبة غنية بالنكهة.", "category": "أسماك ومأكولات بحرية", "ingredients": ["سمك النازلي", "ثوم", "بقدونس طازج", "توابل", "ليمون", "صلصة الطماطم"], "nutritionSummary": "الطاقة: 110 سعرة حرارية، البروتين: 13 غ، الكربوهيدرات: 5 غ، الدهون: 4 غ، الألياف: 1 غ، فيتامين C: 10 ملغ"}}'::jsonb WHERE "id" = 'prod-whiting-kefta-in-tomato-sauce';
UPDATE "Product" SET "translations" = '{"ar": {"name": "صلصة البشاميل", "description": "صلصة بشاميل كريمية من الحليب الطازج والزبدة والتوابل — مثالية للمعكرونة واللازانيا والخضار.", "category": "صلصات وتوابل", "ingredients": ["حليب", "زبدة", "دقيق", "ملح", "فلفل أسود", "توابل"], "nutritionSummary": "الطاقة: 120 سعرة حرارية، البروتين: 3 غ، الكربوهيدرات: 8 غ، الدهون: 8 غ، الكالسيوم: 110 ملغ"}}'::jsonb WHERE "id" = 'prod-b-chamel-sauce';
UPDATE "Product" SET "translations" = '{"ar": {"name": "صلصة البولونيز", "description": "صلصة بولونيز غنية من الطماطم الناضجة واللحم المفروم والأعشاب العطرية — مثالية لأطباق المعكرونة المفضلة لديك.", "category": "صلصات وتوابل", "ingredients": ["طماطم", "لحم بقري مفروم", "ثوم", "بصل", "بقدونس", "ورق الغار", "ملح", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 110 سعرة حرارية، البروتين: 5 غ، الكربوهيدرات: 7 غ، الدهون: 6 غ، الألياف: 2 غ، الحديد: 1.2 ملغ"}}'::jsonb WHERE "id" = 'prod-bolognese-sauce';
UPDATE "Product" SET "translations" = '{"ar": {"name": "مايونيز", "description": "مايونيز كريمي من البيض وزيت الزيتون الممتاز والخردل — مثالي للسندويشات والسلطات والصلصات.", "category": "صلصات وتوابل", "ingredients": ["بيض", "زيت الزيتون", "خردل", "ملح"], "nutritionSummary": "الطاقة: 700 سعرة حرارية، البروتين: 2 غ، الكربوهيدرات: 1 غ، الدهون: 76 غ، الألياف: 0 غ، فيتامين E: 15 ملغ"}}'::jsonb WHERE "id" = 'prod-mayonnaise';
UPDATE "Product" SET "translations" = '{"ar": {"name": "صلصة الطماطم", "description": "صلصة طماطم غنية من الطماطم الناضجة والثوم والأعشاب وزيت الزيتون — مثالية للمعكرونة والبيتزا ووصفاتك المفضلة.", "category": "صلصات وتوابل", "ingredients": ["طماطم", "ثوم", "بصل", "بقدونس", "ورق الغار", "ملح", "توابل", "زيت الزيتون"], "nutritionSummary": "الطاقة: 60 سعرة حرارية، البروتين: 1.5 غ، الكربوهيدرات: 7 غ، الدهون: 2.5 غ، الألياف: 1.5 غ، فيتامين C: 12 ملغ"}}'::jsonb WHERE "id" = 'prod-tomato-sauce';
UPDATE "Product" SET "translations" = '{"ar": {"name": "خردل بالحبوب الكاملة", "description": "خردل بالحبوب الكاملة من مكوّنات طبيعية بسيطة — يضيف نكهة حادة وقوامًا مميزًا للسندويشات والصلصات والتتبيلات.", "category": "صلصات وتوابل", "ingredients": ["بذور الخردل", "ماء", "ملح"], "nutritionSummary": "الطاقة: 120 سعرة حرارية، البروتين: 6 غ، الكربوهيدرات: 8 غ، الدهون: 7 غ، الألياف: 5 غ، الحديد: 1.5 ملغ"}}'::jsonb WHERE "id" = 'prod-wholegrain-mustard';
UPDATE "Plan" SET "translations" = '{"ar": {"name": "صندوق المخزن", "summary": "أساسيات تدوم طويلًا في الخزانة — دهن ومنتج فاكهة وصلصة، مع مكان لمنتج إضافي."}}'::jsonb WHERE "id" = 'plan-pantry';
UPDATE "Plan" SET "translations" = '{"ar": {"name": "صندوق الأطعمة الحيّة", "summary": "مخمّرات طازجة مبرّدة — مشروب حيّ ومنتج ألبان مخمّر وخضار مخمّرة كل أسبوع."}}'::jsonb WHERE "id" = 'plan-living';
UPDATE "Plan" SET "translations" = '{"ar": {"name": "صندوق الساحل", "summary": "من البحر إلى المائدة — نوعان من السمك المتبّل، وصلصة للتقديم، وخضار اختيارية."}}'::jsonb WHERE "id" = 'plan-coastal';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "دهن", "description": "اختر زبدة مكسرات أو بذور."}}'::jsonb WHERE "id" = 'pantry-spread';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "منتج فاكهة", "description": "اختر مربّى أو مركّزًا أو فاكهة محفوظة."}}'::jsonb WHERE "id" = 'pantry-jam';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "صلصة", "description": "اختر صلصة أساسية أو توابل."}}'::jsonb WHERE "id" = 'pantry-sauce';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "دهن إضافي", "description": "دهن ثانٍ اختياري لهذا الشهر."}}'::jsonb WHERE "id" = 'pantry-extra';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "مشروب مخمّر", "description": "اختر مشروبًا حيًّا مخمّرًا."}}'::jsonb WHERE "id" = 'living-beverage';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "ألبان مخمّرة", "description": "اختر جبنًا أو منتج ألبان مخمّرًا."}}'::jsonb WHERE "id" = 'living-dairy';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "خضار مخمّرة", "description": "اختر خضارًا متبّلة أو مخمّرة."}}'::jsonb WHERE "id" = 'living-vegetable';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "مشروب إضافي", "description": "مشروب ثانٍ اختياري لهذا الأسبوع."}}'::jsonb WHERE "id" = 'living-beverage-2';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "السمك 1", "description": "اختر سمكًا متبّلًا أو كفتة سمك."}}'::jsonb WHERE "id" = 'coastal-fish-1';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "السمك 2", "description": "اختر نوعًا ثانيًا من السمك للصندوق."}}'::jsonb WHERE "id" = 'coastal-fish-2';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "صلصة", "description": "اختر صلصة للتقديم معه."}}'::jsonb WHERE "id" = 'coastal-sauce';
UPDATE "PlanSlot" SET "translations" = '{"ar": {"label": "خضار", "description": "خضار مخمّرة اختيارية."}}'::jsonb WHERE "id" = 'coastal-vegetable';
